version: '3.8'

services:
  # The Python application service
  app:
    # Build the image from the Dockerfile in the current directory
    build: .
    # Set the container name for easier identification
    container_name: facebooksummarizer_dev
    # Load environment variables from the .env file
    env_file:
      - .env
    # Override DOCKER_ENV to true specifically for this containerized environment
    environment:
      - DOCKER_ENV=true # Indicate running in Docker
      - HEADLESS_MODE=false # Set to false to enable browser GUI
    # Mount the project directory to the container for live code updates
    volumes:
      - ./db:/app/db
    # Ensure the 'selenium' service starts before the 'app' service
    depends_on:
      - selenium

  # The Selenium standalone Chrome browser service
  selenium:
    # Use the official Selenium image with debugging tools
    image: selenium/standalone-chrome:latest
    container_name: selenium_chrome
    # Set the shared memory size to prevent browser crashes
    shm_size: '1g'
    # Map ports from the container to the host machine
    ports:
      - "7900:7900"  # noVNC for web browser viewing
    restart: unless-stopped